#ifndef BOARD_WAVESHARE_PHOTOPAINTER_73_H
#define BOARD_WAVESHARE_PHOTOPAINTER_73_H

#include "driver/gpio.h"

// Board Info
#define BOARD_HAL_NAME "waveshare_photopainter_73"
#define BOARD_HAL_TYPE BOARD_TYPE_WAVESHARE_PHOTOPAINTER

// Button Definitions
#define BOARD_HAL_WAKEUP_KEY GPIO_NUM_0  // BOOT button
#define BOARD_HAL_ROTATE_KEY GPIO_NUM_4  // Usage: Wakeup + Rotate
#define BOARD_HAL_CLEAR_KEY GPIO_NUM_NC  // Not supported

// E-Paper Display Pins (Spectra E6)
#define BOARD_HAL_EPD_DC_PIN GPIO_NUM_8
#define BOARD_HAL_EPD_CS_PIN GPIO_NUM_9
#define BOARD_HAL_EPD_SCK_PIN GPIO_NUM_10
#define BOARD_HAL_EPD_MOSI_PIN GPIO_NUM_11
#define BOARD_HAL_EPD_RST_PIN GPIO_NUM_12
#define BOARD_HAL_EPD_BUSY_PIN GPIO_NUM_13

// Display Configuration
#define BOARD_HAL_DISPLAY_ROTATION_DEG 180
#define BOARD_HAL_DISPLAY_WIDTH 800
#define BOARD_HAL_DISPLAY_HEIGHT 480

#endif  // BOARD_WAVESHARE_PHOTOPAINTER_73_H
